added exception handling
added features / changes in v2022.40.101 @ 2024-08-06
===================================================

added exception handling to catch bad device data, ie:
    if   int(digit) < 10:	last = "00"
         ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''